library(tidyverse)
library(lubridate)
library(plotly)
library(htmlwidgets)
options(timeout=120)
download.file("https://data.stopcovid19.metro.tokyo.lg.jp/130001_tokyo_covid19_patients_per_report_date.csv", "130001_tokyo_covid19_patients_per_report_date.csv", "auto")
t000<-read_csv(file="130001_tokyo_covid19_patients_per_report_date.csv",col_names = FALSE,skip=1)
t02<-t000%>%rename(date=X4,cases=X5,ma7=X7,seven_days_ratio=X11)
t02$date<-ymd(t02$date)
fig01<-plot_ly(x=t02$date,y=t02$cases,type="bar",name="cases")%>%add_trace(x=t02$date,y=t02$ma7,type="scatter",mode="line",name="moving_ave")
htmlwidgets::saveWidget(fig01,file="docs/moving_ave.html",selfcontained = FALSE)
fig02<-plot_ly(x=t02$date,y=round(t02$seven_days_ratio,3),type="scatter",mode="markers")%>%layout(title = "Whole_tokyo")
htmlwidgets::saveWidget(fig02,file="docs/whole_tokyo_ratio.html",selfcontained = FALSE)
# quit(save=”no”)
